name: New Component
description: Add and track a new FRC1250 produced component
title: "FRC1250-26-00xx <your_description_here>"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this form to register and track a newly designed or fabricated component.

  - type: dropdown
    id: subsystem
    attributes:
      label: Subsystem
      description: Primary robot subsystem this component belongs to
      options:
        - label: CHASSIS
          value: subsystem:CHASSIS
        - label: INTAKE
          value: subsystem:INTAKE
        - label: FUEL_MGMT
          value: subsystem:FUEL_MGMT
        - label: SHOOTER
          value: subsystem:SHOOTER
        - label: CLIMB
          value: subsystem:CLIMB
    validations:
      required: true
    label:
      - "subsystem:{{value}}"

  - type: dropdown
    id: component_type
    attributes:
      label: Component Type
      description: How this component is produced or defined
      options:
        - label: FDM - 3D Printed
          value: component_type:FDM
        - label: CNC - Made by a robot
          value: component_type:CNC
        - label: DWG - Made/modified by a person
          value: component_type:DWG
        - label: ASM - Assembly
          value: component_type:ASM
    validations:
      required: true
      label:
        - "component_type:{{value}}"

  - type: textarea
    id: description
    attributes:
      label: Component Description
      description: What is this component and what does it do?
      placeholder: Brief functional description
    validations:
      required: true
    label:
      - "component_type:{{value}}"

  - type: textarea
    id: notes
    attributes:
      label: Notes / Links
      description: Links to references or additional context
