name: New Component
description: Add and track a new FRC1250 produced component
title: "FRC1250-26-00xx <your_description_here>"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this form to register and track a newly designed or fabricated component.

  - type: textarea
    id: description
    attributes:
      label: Component Description
      description: What is this component and what does it do?
      placeholder: Brief functional description
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / Links
      description: Links to references or additional context
